### ISSUE TITLE
Cannot install with latest react

### ISSUE THREAD

**Issue by alextownleymakes** [diegomura/react-pdf-site#76]
`npm ERR! While resolving: pdfer@0.1.0
npm ERR! Found: react@18.1.0
npm ERR! node_modules/react
npm ERR!   react@"^18.1.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.6 || ^17.0.0" from @react-pdf/renderer@2.1.2
npm ERR! node_modules/@react-pdf/renderer
npm ERR!   @react-pdf/renderer@"*" from the root project`

This is a brand new project with no other dependencies installed. 

Reproducible by:

npx create-react-app demo
cd demo
npm install @react-pdf/renderer --save

**Comment by diegomura** [comment]
Hey! This issue has been already created in the projects repo (this is only the site repo). Please check it out

**Comment by alextownleymakes** [comment]
Didn't realize I was creating it from the wrong repo, my mistake!
